# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnyConnect < Formula
  desc "Software to operate any connect easiser."
  homepage "https://github.com/TomoyukiSugiyama/any-connect"
  version "0.3.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TomoyukiSugiyama/any-connect/releases/download/v0.3.2/any-connect_0.3.2_darwin_arm64.tar.gz"
      sha256 "79365adaa805948928606e041dfa88a7d9b1f4c6b72345c26fb385e32f9ab64e"

      def install
        bin.install "any-connect"
      end
    end
  end

  on_linux do
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TomoyukiSugiyama/any-connect/releases/download/v0.3.2/any-connect_0.3.2_linux_arm64.tar.gz"
        sha256 "fd72f9d6f5fcddfe00ebd92041c29f04448f5c8ccc3586b7f650fef33c287253"

        def install
          bin.install "any-connect"
        end
      end
    end
  end

  def caveats
    <<~EOS
      any-connect need to use AnyConnect provided by cisco.
    EOS
  end

  test do
    system "#{bin}/any-connect help"
  end
end
