# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnyConnect < Formula
  desc "Software to operate any connect easiser."
  homepage "https://github.com/TomoyukiSugiyama/any-connect"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TomoyukiSugiyama/any-connect/releases/download/v0.1.2/any-connect_0.1.2_darwin_arm64.tar.gz"
      sha256 "b6f1bd0ac71ccc57ce873ad356c8b0baecdbcd3ecf166c97c8afec8cf6b6d989"

      def install
        bin.install "any-connect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomoyukiSugiyama/any-connect/releases/download/v0.1.2/any-connect_0.1.2_linux_arm64.tar.gz"
      sha256 "7510d66e5d03881449d9c6bdb3063a511502599075802dee09c796b92e1af3a5"

      def install
        bin.install "any-connect"
      end
    end
  end

  def caveats
    <<~EOS
      any-connect need to use AnyConnect provided by cisco.
    EOS
  end

  test do
    system "#{bin}/any-connect help"
  end
end
