# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudSqlProxyV2Operator < Formula
  desc "Software to operate cloud-sql-proxy easiser."
  homepage "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator/releases/download/v0.1.4/cloud-sql-proxy-v2-operator_0.1.4_Darwin_arm64.tar.gz"
      sha256 "66a92b363ffaf4b53f0d844a341005aeeabdede184bdc8d2196f01d717063911"

      def install
        bin.install "cloud-sql-proxy-v2-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator/releases/download/v0.1.4/cloud-sql-proxy-v2-operator_0.1.4_linux_arm64.tar.gz"
      sha256 "4b652de338bf20a4fefcdd4f8f6b70c9dce221ab2af814699550bfec73a3a4b1"

      def install
        bin.install "cloud-sql-proxy-v2-operator"
      end
    end
  end

  def caveats
    <<~EOS
      cloud-sql-proxy-v2-operator need to install gcloud cli from https://cloud.google.com/sdk/docs/install?hl=ja and cloud-sql-proxy v2.x.x from https://cloud.google.com/sql/docs/postgres/sql-proxy?hl=ja#install
    EOS
  end

  test do
    system "#{bin}/cloud-sql-proxy-v2-operator version"
  end
end
