# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudSqlProxyV2Operator < Formula
  desc "Software to operate cloud-sql-proxy easiser."
  homepage "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator/releases/download/v0.2.0/cloud-sql-proxy-v2-operator_0.2.0_Darwin_arm64.tar.gz"
      sha256 "af0b5c2fa9e27a1962c03a4abe4a6f5e07a6fbd25aec0c9b5bbe8f502e4ecfd8"

      def install
        bin.install "cloud-sql-proxy-v2-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator/releases/download/v0.2.0/cloud-sql-proxy-v2-operator_0.2.0_linux_arm64.tar.gz"
      sha256 "d22fe84f99d5365bb6af0da63e234da6c3d05099f59c36649d34c21042f1a062"

      def install
        bin.install "cloud-sql-proxy-v2-operator"
      end
    end
  end

  def caveats
    <<~EOS
      cloud-sql-proxy-v2-operator need to install gcloud cli from https://cloud.google.com/sdk/docs/install?hl=ja and cloud-sql-proxy v2.x.x from https://cloud.google.com/sql/docs/postgres/sql-proxy?hl=ja#install
    EOS
  end

  test do
    system "#{bin}/cloud-sql-proxy-v2-operator version"
  end
end
