# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudSqlProxyV2Operator < Formula
  desc "Software to operate cloud-sql-proxy easiser."
  homepage "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator/releases/download/v0.3.4/cloud-sql-proxy-v2-operator_Darwin_arm64.tar.gz"
      sha256 "e497c5e5b0c9ebd843c7cc5e04a40e5e002424938c752b019eec4fa72bc93deb"

      define_method(:install) do
        bin.install "cloud-sql-proxy-v2-operator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomoyukiSugiyama/cloud-sql-proxy-v2-operator/releases/download/v0.3.4/cloud-sql-proxy-v2-operator_Linux_arm64.tar.gz"
      sha256 "15f927b25e0f08212c4418cfaa8ce25c4353caa0ed4583bfcfc01c82b62e3262"
      define_method(:install) do
        bin.install "cloud-sql-proxy-v2-operator"
      end
    end
  end

  def caveats
    <<~EOS
      cloud-sql-proxy-v2-operator need to install gcloud cli from https://cloud.google.com/sdk/docs/install?hl=ja and cloud-sql-proxy v2.x.x from https://cloud.google.com/sql/docs/postgres/sql-proxy?hl=ja#install
    EOS
  end

  test do
    system "#{bin}/cloud-sql-proxy-v2-operator version"
  end
end
